package mk.ukim.finki.aggregatorservice.model;

import java.time.Instant;

/**
 * Alert generated by the aggregator.
 */
public class AlertMessage {
    private String city;
    private String signal;
    private String level;     // GREEN, YELLOW, RED
    private double value;     // aggregated value (avg)
    private double threshold; // threshold where we changed level
    private Instant timestamp;
    private String reason;

    public AlertMessage() {}

    // getters/setters...
}